server:
  port: 8080

mini-db-router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 4
      default: db00
      routerKey: uId
      list: db01,db02
      db00:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lottery
        username: wxy
        password: weixing5shishi
      db01:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lottery_01
        username: wxy
        password: weixing5shishi
      db02:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/lottery_02
        username: wxy
        password: weixing5shishi


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis_config.xml


dubbo:
  application:
    name: Lottery
    version: 1.0.0
  registry:
    address: N/A
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.it.lottery.rpc
